# Generated by Django 3.0.2 on 2020-11-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_auto_20201105_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
