# Generated by Django 3.0.2 on 2020-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_auto_20201106_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
