# Generated by Django 3.0.6 on 2020-11-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0006_auto_20201106_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_decision', to='Report.Activity'),
        ),
        migrations.AlterField(
            model_name='person',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_person', to='Report.Activity'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_problem', to='Report.Activity'),
        ),
    ]
