# Generated by Django 3.0.6 on 2020-11-07 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0007_auto_20201106_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='person',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='activity',
        ),
    ]
