# Generated by Django 3.0.6 on 2020-11-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0008_auto_20201107_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
