# Generated by Django 3.0.6 on 2020-11-07 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0010_auto_20201107_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Report.ProjectManager', unique=True),
        ),
    ]
