# Generated by Django 3.0.6 on 2020-11-07 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0011_auto_20201107_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='project_manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Report.ProjectManager'),
        ),
    ]
